Repository unchain-dev/verifiable-membership, pull requests merged in 2023-01, with the labels that each got.

#8 フローの画像データとフロントエンド仕様書に少し追記しました
  packages/vc/README.md
  packages/vc/assets/other-img/flow.png
  spec/client.md
Labels: documentation

#7 TypeScriptに変更してみました
  package.json
  packages/contract/package.json
  packages/vc/constants/index.ts
  packages/vc/package.json
  packages/vc/scripts/convert.ts
  packages/vc/scripts/generate-unsign-vc.js
  packages/vc/scripts/generate-unsign-vc.ts
  packages/vc/types/index.d.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#9 シーケンス図をmermaidで記述
  packages/vc/assets/other-img/flow.png
  spec/architecture.md
Labels: documentation

#11 スクリプトの追加・画面イメージ案を追加
  README.md
  package.json
  packages/vc/constants/index.ts
  packages/vc/hosting/did.json
  packages/vc/hosting/profile.json
  packages/vc/hosting/sample/did.json
  packages/vc/hosting/sample/jwk.json
  packages/vc/hosting/sample/profile.json
  packages/vc/package.json
  packages/vc/scripts/convert.ts
  packages/vc/scripts/generate-did.ts
  packages/vc/scripts/generate-profile.ts
  packages/vc/types/trust__keyto.d.ts
  spec/assets/imgs/VC一覧画面.png
  spec/assets/imgs/VC検証画面.png
  spec/assets/imgs/VC発行画面.png
  spec/assets/imgs/unchainSite.png
  spec/assets/imgs/vcs_sample.png
  spec/assets/imgs/verify_sample.png
  spec/client.md
  tsconfig.json
  yarn.lock
Labels: documentation, enhancement
